services:
  custom_pytorch_container:
    runtime: nvidia
    build: ./docker/
    image: custom_pytorch
    ipc: host
    volumes:
      - ./:/workspace
      - /tmp/.X11-unix:/tmp/.X11-unix
      - $HOME/.Xauthority:/root/.Xauthority:ro
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility,graphics,display
      - DISPLAY=unix$DISPLAY
    entrypoint: /bin/bash
